name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
          bundler-cache: true

      - name: Lint code for consistent style
        run: bin/rubocop -f github

  test:
    runs-on: ubuntu-latest
    # Rode em paralelo; se quiser exigir lint antes, adicione: needs: [lint]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
          bundler-cache: true

      - name: Run RSpec
        env:
          RAILS_ENV: test
        run: |
          bundle exec rspec --format progress --format RspecJunitFormatter --out rspec.xml || exit_code=$?
          echo "exit_code=${exit_code:-0}" >> $GITHUB_OUTPUT
          exit ${exit_code:-0}

      - name: Upload RSpec report (jUnit)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: rspec-report
          path: rspec.xml

